galeria/urls.py
from django.urls import path
from .views import index, crud,alumnos_findEdit
from galeria import views
from .views import ArticuloListView, ArticuloCreateView, ArticuloUpdateView, ArticuloDeleteView
from .views import verificar_articulos
from . import views
from django.contrib.auth import views as auth_views
urlpatterns = [

    #LoginLogout
    path('login/', auth_views.LoginView.as_view(template_name='galeria/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('tipos_productos/', views.lista_tipos_productos, name='lista_tipos_productos'),
    path('tipos_productos/crear/', views.crear_tipo_producto, name='crear_tipo_producto'),
    path('tipos_productos/editar/<int:id>/', views.editar_tipo_producto, name='editar_tipo_producto'),
    path('tipos_productos/eliminar/<int:id>/', views.eliminar_tipo_producto, name='eliminar_tipo_producto'),
    path('proveedores/', views.lista_proveedores, name='lista_proveedores'),
    path('proveedores/crear/', views.crear_proveedor, name='crear_proveedor'),
    path('proveedores/editar/<int:id>/', views.editar_proveedor, name='editar_proveedor'),
    path('proveedores/eliminar/<int:id>/', views.eliminar_proveedor, name='eliminar_proveedor'),
    path('crud/', views.crud, name='crud'),
    path('crud_generos/', views.crud_generos, name='crud_generos'),
    path('articulos/', views.articulos, name='articulos'),
    path('articulos/crear/', views.crear_articulo, name='crear_articulo'),
    path('articulos/editar/<int:id>/', views.editar_articulo, name='editar_articulo'),
    path('articulos/eliminar/<int:id>/', views.eliminar_articulo, name='eliminar_articulo'),


    #Login
    path('login/', auth_views.LoginView.as_view(template_name='galeria/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    
    #Htmls
    path('', views.index, name='index'),
    path('anime/', views.anime, name='anime'),
    path('games/', views.games, name='games'),
    path('contacto/', views.contacto, name='contacto'),
    path('comprar/', views.comprar, name='comprar'),
    path('polera1/', views.polera1, name='polera1'),
    path('polera2/', views.polera2, name='polera2'),
    path('polera3/', views.polera3, name='polera3'),
    path('polera4/', views.polera4, name='polera4'),
    path('api/', views.api, name='api'),
    path('rock/', views.rock, name='rock'),
    
    #clientes

    path('clientes/', views.cliente_lista, name='cliente_lista'),
    path('clientes/<int:pk>/', views.cliente_detalle, name='cliente_detalle'),
    path('clientes/nuevo/', views.cliente_crear, name='cliente_crear'),
    path('clientes/<int:pk>/editar/', views.cliente_editar, name='cliente_editar'),
    path('clientes/<int:pk>/eliminar/', views.cliente_eliminar, name='cliente_eliminar'),

    #contacto
    path('contacto/', views.contacto_crear, name='contacto_crear'),
    path('contacto/exito/', views.contacto_exito, name='contacto_exito'),
    path('contactos/', views.contacto_lista, name='contacto_lista'),


    #Crud

    path('crud', views.crud, name='crud'),
    path('galeria/alumnosAdd', views.alumnosAdd, name='alumnosAdd'),
    path('galeria/alumnos_del/<str:pk>', views.alumnos_del, name='alumnos_del'),
    path('galeria/alumnos_findEdit/<str:pk>', views.alumnos_findEdit, name='alumnos_findEdit'),
    path('galeria/alumnosUpdate', views.alumnosUpdate, name='alumnosUpdate'),

    path('crud_generos', views.crud_generos, name='crud_generos'),
    path('generosAdd', views.generosAdd, name='generosAdd'),
    path('generos_del/<str:pk>', views.generos_del, name='generos_del'),
    path('generos_edit/<str:pk>', views.generos_edit, name='generos_edit'),
    path('galeria/alumnosAdd/', views.alumnosAdd, name='alumnos_add'),
    
    #articulos (Productos)
    path('articulos/', ArticuloListView.as_view(), name='articulo-list'),
    path('articulos/new/', ArticuloCreateView.as_view(), name='articulo-create'),
    path('articulos/<str:pk>/edit/', ArticuloUpdateView.as_view(), name='articulo-update'),
    path('articulos/<str:pk>/delete/', ArticuloDeleteView.as_view(), name='articulo-delete'),
    path('verificar_articulos/', verificar_articulos, name='verificar-articulos'),


    #Tipoprod
    path('tipos_productos/', views.lista_tipos_productos, name='lista_tipos_productos'),
    path('tipos_productos/crear/', views.crear_tipo_producto, name='crear_tipo_producto'),
    path('tipos_productos/editar/<int:id>/', views.editar_tipo_producto, name='editar_tipo_producto'),
    path('tipos_productos/eliminar/<int:id>/', views.eliminar_tipo_producto, name='eliminar_tipo_producto'),

    #Proveedores

    path('proveedores/', views.lista_proveedores, name='lista_proveedores'),
    path('proveedores/crear/', views.crear_proveedor, name='crear_proveedor'),
    path('proveedores/editar/<int:id>/', views.editar_proveedor, name='editar_proveedor'),
    path('proveedores/eliminar/<int:id>/', views.eliminar_proveedor, name='eliminar_proveedor'),


    #Tienda
    path('', views.index, name='index'),
    path('store/', views.store, name='store'),



]


mysite/urls.py
from django.contrib import admin
from django.urls import path, include


# mysite/urls.py

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('galeria.urls')),
]

galeria/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

#Articulos

class Articulo(models.Model):
    sku = models.CharField(max_length=100, unique=True)
    nombre = models.CharField(max_length=200)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.IntegerField()

    def __str__(self):
        return self.nombre



class Proveedor(models.Model):
    NOMBRE_EMPRESA_MAX_LENGTH = 100
    RUT_MAX_LENGTH = 12
    RAZON_SOCIAL_MAX_LENGTH = 100
    PAIS_MAX_LENGTH = 50

    TIPOS_PAGO = [
        ('CR', 'Crédito'),
        ('CO', 'Contado')
    ]

    nombre_empresa = models.CharField(max_length=NOMBRE_EMPRESA_MAX_LENGTH)
    rut = models.CharField(max_length=RUT_MAX_LENGTH, unique=True)
    razon_social = models.CharField(max_length=RAZON_SOCIAL_MAX_LENGTH)
    pais = models.CharField(max_length=PAIS_MAX_LENGTH)
    tipo_pago = models.CharField(max_length=2, choices=TIPOS_PAGO)

    def __str__(self):
        return self.nombre_empresa

class TipoProducto(models.Model):
    nombre = models.CharField(max_length=100)
    marca = models.CharField(max_length=100)
    procedencia = models.CharField(max_length=100)
    codigo = models.IntegerField(unique=True)

    def __str__(self):
        return f"{self.nombre} - {self.marca}"


class Articulo(models.Model):
    sku = models.CharField(max_length=50, primary_key=True, unique=True)
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.IntegerField()

    def __str__(self):
        return self.nombre

class Region(models.Model):
    id_region = models.IntegerField(primary_key=True)
    nom_region = models.CharField(max_length=30)

    def __str__(self):
        return self.nom_region

class Comuna(models.Model):
    id_comuna = models.IntegerField(primary_key=True)
    nom_comuna = models.CharField(max_length=30)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)

    def __str__(self):
        return self.nom_comuna

class Cliente(models.Model):
    rut_cli = models.CharField(max_length=20, primary_key=True)
    nombres = models.CharField(max_length=40)
    apellidos = models.CharField(max_length=40)
    email = models.EmailField(max_length=40)
    direccion = models.CharField(max_length=40)
    telefono = models.CharField(max_length=20)
    comuna = models.ForeignKey(Comuna, on_delete=models.CASCADE)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)

class CategoriaPolera(models.Model):
    id_categoria = models.IntegerField(primary_key=True)
    nombre_cat = models.CharField(max_length=30)

class Producto(models.Model):
    id_productos = models.IntegerField(primary_key=True)
    nombre_prod = models.CharField(max_length=30)
    descrip_produc = models.CharField(max_length=40)
    precio_produc = models.DecimalField(max_digits=20, decimal_places=2)
    stock_produc = models.IntegerField()
    categoria = models.ForeignKey(CategoriaPolera, on_delete=models.CASCADE)

class DetallePedido(models.Model):
    id_detalle = models.IntegerField(primary_key=True)
    cantidad = models.IntegerField()
    precio = models.DecimalField(max_digits=20, decimal_places=2)
    categoria_polera = models.ForeignKey(CategoriaPolera, on_delete=models.CASCADE)

class Pedido(models.Model):
    id_pedido = models.IntegerField(primary_key=True)
    fecha = models.DateField()
    total_pedi = models.DecimalField(max_digits=20, decimal_places=2)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    detalle_pedido = models.ForeignKey(DetallePedido, on_delete=models.CASCADE)


class Contacto(models.Model):
    correo = models.EmailField(max_length=100)
    nombre_completo = models.CharField(max_length=100)
    telefono = models.CharField(max_length=15)
    consulta = models.TextField()

    def __str__(self):
        return self.nombre_completo
    
class Genero(models.Model):
    id_genero = models.AutoField(primary_key=True)
    genero = models.CharField(max_length=100)

    def __str__(self):
        return self.genero

class Alumno(models.Model):
    rut = models.CharField(max_length=12, primary_key=True)
    nombre = models.CharField(max_length=100)
    apellido_paterno = models.CharField(max_length=100)
    apellido_materno = models.CharField(max_length=100)
    fecha_nacimiento = models.DateField()
    genero = models.ForeignKey(Genero, on_delete=models.CASCADE) 
    telefono = models.CharField(max_length=15)
    email = models.EmailField()
    direccion = models.CharField(max_length=255)
    activo = models.BooleanField(default=True)

    def __str__(self):
        return self.nombre
    
class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    published_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title

galeria/forms.py
from django import forms
from .models import Cliente, Contacto
from django.forms import ModelForm
from .models import Genero
from .models import Articulo
from .models import TipoProducto
from .models import Proveedor
from .models import Articulo


class ProveedorForm(forms.ModelForm):
    class Meta:
        model = Proveedor
        fields = ['nombre_empresa', 'rut', 'razon_social', 'pais', 'tipo_pago']


class TipoProductoForm(forms.ModelForm):
    class Meta:
        model = TipoProducto
        fields = ['nombre', 'marca', 'procedencia', 'codigo']

class ArticuloForm(forms.ModelForm):
    class Meta:
        model = Articulo
        fields = ['sku', 'nombre', 'descripcion', 'precio', 'stock']


class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['rut_cli', 'nombres', 'apellidos', 'email', 'direccion', 'telefono', 'comuna', 'region']

class ContactoForm(forms.ModelForm):
    class Meta:
        model = Contacto
        fields = ['correo', 'nombre_completo', 'telefono', 'consulta']
        labels = {
            'correo': 'Correo',
            'nombre_completo': 'Nombre Completo',
            'telefono': 'Teléfono',
            'consulta': 'Consulta',
        }

class GeneroForm(ModelForm):
    class Meta:
        model = Genero
        fields = ["genero",]
        labels = {'genero': 'Género', }

class ArticuloForm(forms.ModelForm):
    class Meta:
        model = Articulo
        fields = ['sku', 'nombre', 'descripcion', 'precio', 'stock']

galeria/templates/galeria/Api.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>API</title>
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="{% static 'consumo.js' %}"></script>
</head>
<body>
    <div class="container mt-5">
        <h1>Consumo de Dolar</h1>
        <h2>Valor Dolar</h2>
        <div id="uf-value">
            <p>Cargando Valor...</p>
        </div>
    </div>
</body>
</html>

galeria/templates/galeria/alumnos_list.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar datos Clientes</title>
    <!-- Bootstrap CSS -->
    {% load static %}
    <link href="{% static 'css/estilos.css' %}" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <!-- Load static files -->
    

    <link href="{% static 'css/estilos.css' %}" rel="stylesheet">
</head>
    
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'index' %}">SOMOS UWU</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">INICIO</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'anime' %}">ANIME</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'games' %}">GAMES</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'rock' %}">ROCK</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'alumnos_add' %}">CONTACTO</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        <h1 class="text-center text-white">Editar datos Clientes</h1><br><br>

        <button type="button" class="btn btn-primary">
            <a href="{% url 'alumnosAdd' %}" class="text-white">Agregar Contacto</a>
        </button>

        <div id="idMensajes" class="alert alert-info mt-3">
            {% if mensaje %}
                {{ mensaje }}
            {% endif %}
        </div>

        <table class="table table-bordered mt-3 text-center text-white">
            {% if alumnos %}
                <thead>
                    <tr>
                        <th>Rut</th>
                        <th>Nombre</th>
                        <th>Apellido</th>
                        <th>Email</th>
                        <th>Eliminar</th>
                        <th>Modificar</th>
                    </tr>
                </thead>
                <tbody>
                    {% for x in alumnos %}
                        <tr>
                            <td>{{ x.rut }}</td>
                            <td>{{ x.nombre }}</td>
                            <td>{{ x.apellido_paterno }}</td>
                            <td>{{ x.email }}</td>
                            <td><a href="{% url 'alumnos_del' pk=x.rut %}" class="btn btn-danger">Eliminar</a></td>
                            <td><a href="{% url 'alumnos_findEdit' pk=x.rut %}" class="btn btn-warning">Modificar</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            {% endif %}
        </table>
    </div>

    <div class="text-center">
        <center>
            <div class="center">
                <a href="{% url 'dashboard' %}" class="btn btn-primary">VOLVER A MENÚ</a>
            </div>
          </center>
            </div>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>
        $(document).ready(function(){
            $("#idMensajes").delay(2000).fadeOut("slow");
        });
    </script>
</body>
</html>

galeria/templates/galeria/anime.html
<!doctype html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>UWU Art</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'index' %}">SOMOS UWU</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">INICIO</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'anime' %}">ANIME</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'games' %}">GAMES</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'rock' %}">ROCK</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'store' %}">TIENDA</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'alumnos_add' %}">CONTACTO</a>
                </li>
            </ul>
        </div>
    </nav>

    <h3 class="center-text">TU ZONA ANIME</h3>
    <div class="d-flex flex-wrap justify-content-around">
        <div class="card bg-dark text-white">
            <img src="{% static 'imagenes/collage.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
                <center>
                    <h5 class="card-title">ENCUENTRA TU CUADRO FAVORITO</h5>
                    <p class="card-text">MUCHOS TAMAÑOS</p>
                    <p class="card-text">Precio $10.990</p>
                    <p class="card-text">Envíos a todo Chile y al Extranjero</p>
                    <a href="{% url 'comprar' %}" class="btn btn-primary">COMPRAR</a>
                    <a href="{% url 'index' %}" class="btn btn-secondary">VOLVER</a>
                </center>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

galeria/templates/galeria/comprar.html
<!doctype html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>UWU Art</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'index' %}">SOMOS UWU</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">INICIO</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'anime' %}">ANIME</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'games' %}">GAMES</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'rock' %}">ROCK</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'contacto' %}">CONTACTO</a>
                </li>
            </ul>
        </div>
    </nav>

    <h1 class="center-text">Formulario de Compra</h1>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <form id="contactForm">
                    <div class="mb-3">
                        <label for="fullName" class="form-label">Nombre completo</label>
                        <input type="text" class="form-control" id="fullName" required>
                        <div class="invalid-feedback">Por favor, ingresa tu nombre completo.</div>
                    </div>

                    <div class="contactForm">
                        <label for="inputEmail" class="form-label">Ingresa tu Correo</label>
                        <input type="email" class="form-control" id="inputEmail" placeholder="tucorreo@gmail.com" required>
                        <div class="invalid-feedback">Favor, ingresar un correo electrónico válido.</div>
                    </div>
                    
                    <div class="form-group">
                        <label for="producto">Producto a Comprar</label>
                        <select class="form-control" id="producto">
                            <option>Camiseta Jujutsu Kaisen</option>
                            <option>Camiseta Saint Seiya</option>
                            <option>Camiseta One Piece</option>
                            <option>Camiseta Hunter X Hunter</option>
                            <option>CD´s Rock</option>
                            <option>Juegos</option>
                        </select>
                    </div>
                    
                    <div class="form-group">
                        <label for="cantidad">Cantidad</label>
                        <input type="number" class="form-control" id="cantidad" required>
                    </div>
                 
                    <div class="mb-3">
                        <label for="phoneInput" class="form-label">Teléfono de contacto</label>
                        <input type="text" class="form-control" id="phoneInput" pattern="[0-9]+" required>
                        <div class="invalid-feedback">Por favor, ingresa un número de teléfono válido.</div>
                    </div>

                    <div class="form-group">
                        <label for="direccion">Dirección de Despacho</label>
                        <input type="text" class="form-control" id="direccion">
                    </div>
                    
                    <div class="form-group">
                        <label for="notas">Notas Adicionales</label>
                        <textarea class="form-control" id="notas" rows="3" required></textarea>
                    </div>
                    
                    <button type="submit" class="btn btn-primary">Enviar</button>
                    <a href="{% url 'index' %}" class="btn btn-secondary">Volver</a>
                </form>
                <div id="thankYouMessage" class="alert alert-success mt-3" style="display: none;">
                    ¡Gracias por tu compra! Se te ha enviado un correo con tu detalle.
                </div>
            </div>
        </div>
    </div>
            
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="{% static 'js/validaciones.js' %}"></script>
</body>
</html>

galeria/templates/galeria/lista_proveedores.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Proveedores</title>
    {% load static %}
    <link href="{% static 'css/estilos.css' %}" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background-color: #898484; /* Cambia este color al que prefieras */
        }
        .center-text {
            text-align: center;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'index' %}">SOMOS UWU</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">INICIO</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'anime' %}">ANIME</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'games' %}">GAMES</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'rock' %}">ROCK</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'alumnos_add' %}">CONTACTO</a>
                </li>
            </ul>
        </div>
    </nav>
    
    <h3 class="center-text text-white">Lista de Proveedores</h3>
    <div class="container">
        <a href="{% url 'crear_proveedor' %}" class="btn btn-primary mb-3">Agregar</a>
        <table class="table">
            <thead>
                <tr>
                    <th>Nombre Empresa</th>
                    <th>RUT</th>
                    <th>Razón Social</th>
                    <th>País</th>
                    <th>Tipo de Pago</th>
                    <th>Eliminar</th>
                    <th>Modificar</th>
                </tr>
            </thead>
            <tbody>
                {% if proveedores %}
                    {% for proveedor in proveedores %}
                    <tr>
                        <td>{{ proveedor.nombre_empresa }}</td>
                        <td>{{ proveedor.rut }}</td>
                        <td>{{ proveedor.razon_social }}</td>
                        <td>{{ proveedor.pais }}</td>
                        <td>{{ proveedor.get_tipo_pago_display }}</td>
                        <td><a href="{% url 'eliminar_proveedor' proveedor.id %}" class="btn btn-danger">Eliminar</a></td>
                        <td><a href="{% url 'editar_proveedor' proveedor.id %}" class="btn btn-warning">Modificar</a></td>
                    </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td colspan="7">No hay proveedores disponibles.</td>
                    </tr>
                {% endif %}
            </tbody>
        </table>
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script>
        $(document).ready(function(){
            $("#idMensajes").delay(2000).fadeOut("slow");
        });
    </script>
    <center>
        <div class="center">
            <a href="{% url 'dashboard' %}" class="btn btn-primary">VOLVER A MENÚ</a>
        </div>
      </center>
</body>
</html>